'use strict';
(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class Game{
 constructor(){this.mode='title';this.titleIndex=0;this.s=null;this.battle=null;this.dialog=null;this.menu=null;this.shop=null;this.notice='';this.noticeT=0;this.last=performance.now();this.bind();requestAnimationFrame(t=>this.loop(t));}
 fresh(){return{map:'home',x:5,y:5,playtime:0,player:{name:'Kael',level:1,xp:0,nextXp:55,hp:100,maxHp:100,mp:24,maxMp:24,str:10,vit:9,magic:8,agi:9,luck:7,job:'wanderer',jobLevel:1,jp:0,nextJp:80,equipment:{weapon:'oldSword',shield:null,head:null,body:'traveler',accessory:'boots'}},inventory:{potion:3,antidote:1},equipment:{},gold:50,quests:{main:'active',necklace:'available',herbs:'available'},flags:{metElder:false,leftTown:false,enteredCave:false,defeatedStoneback:false,necklaceFound:false,necklaceDone:false,herbsDone:false},opened:{},bestiary:{},encounterMeter:0,autosaveUnlocked:false};}
 bind(){const map={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Enter:'confirm',KeyZ:'confirm',Escape:'cancel',KeyX:'cancel',KeyM:'menu'};addEventListener('keydown',e=>{const a=map[e.code];if(a){e.preventDefault();this.input(a)}});document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();this.input(b.dataset.action)}));}
 input(a){if(this.mode==='title')return this.titleInput(a);if(this.mode==='battle'){if(a==='up')this.battle.menu=(this.battle.menu+4)%5;if(a==='down')this.battle.menu=(this.battle.menu+1)%5;if(a==='confirm')this.battle.command(['Attack','Magic','Item','Defend','Flee'][this.battle.menu]);return;}if(this.mode==='gameover'){if(a==='confirm'){const s=SH.Save.read('auto')||SH.Save.read('1');if(s){this.s=s;this.mode='world'}else this.mode='title'}return;}if(this.dialog){if(a==='confirm'||a==='cancel')this.dialog=null;return;}if(this.shop)return this.shopInput(a);if(this.menu)return this.menuInput(a);if(a==='menu')return this.menu={page:'root',index:0};if(a==='confirm')return this.interact();if(['up','down','left','right'].includes(a))this.move(a);}
 titleInput(a){if(a==='up')this.titleIndex=(this.titleIndex+3)%4;if(a==='down')this.titleIndex=(this.titleIndex+1)%4;if(a!=='confirm')return;if(this.titleIndex===0){this.s=this.fresh();this.mode='world';this.dialog='Morning light spills through the window. Mother calls from downstairs: “Kael! Elder Rowan asked for you!”';return;}if(this.titleIndex===1||this.titleIndex===2){const sm=SH.Save.summaries().find(x=>!x.empty);if(sm){this.s=SH.Save.read(sm.slot);this.mode='world';this.notice='Adventure loaded.';this.noticeT=2}else{this.notice='No save data found.';this.noticeT=2}return;}this.notice='Settings live in the in-game menu.';this.noticeT=2;}
 stats(){const p=this.s.player;let attack=p.str,defense=p.vit,agi=p.agi;for(const id of Object.values(p.equipment)){if(!id)continue;const o=SH.DATA.weapons[id]||SH.DATA.armor[id]||{};attack+=o.atk||0;defense+=o.def||0;agi+=o.agi||0;}return{attack,defense,agi};}
 move(a){const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[a],m=SH.MAPS[this.s.map];let nx=clamp(this.s.x+d[0],1,m.w-2),ny=clamp(this.s.y+d[1],1,m.h-2);if((m.solids||[]).some(r=>nx>=r.x&&nx<r.x+r.w&&ny>=r.y&&ny<r.y+r.h))return;this.s.x=nx;this.s.y=ny;for(const w of m.warps||[])if(nx>=w.x&&nx<w.x+w.w&&ny>=w.y&&ny<w.y+w.h){this.s.map=w.to;this.s.x=w.tx;this.s.y=w.ty;if(w.to==='world')this.s.flags.leftTown=true;if(w.to==='cave')this.s.flags.enteredCave=true;if(this.s.autosaveUnlocked)SH.Save.autosave(this.s);this.notice=SH.MAPS[w.to].name;this.noticeT=1.5;return;}if(!m.safe){this.s.encounterMeter+=10+Math.random()*8;if(this.s.encounterMeter>100){this.s.encounterMeter=-45;const table=SH.ENCOUNTERS[m.encounters];this.startBattle(table[Math.floor(Math.random()*table.length)]);}}}
 interact(){const m=SH.MAPS[this.s.map],o=(m.objects||[]).filter(x=>Math.hypot(x.x-this.s.x,x.y-this.s.y)<=2.2).sort((a,b)=>Math.hypot(a.x-this.s.x,a.y-this.s.y)-Math.hypot(b.x-this.s.x,b.y-this.s.y))[0];if(!o){this.notice='Nothing interesting nearby.';this.noticeT=1;return;}if(o.text)return this.dialog=o.text;if(o.chest)return this.chest(o);if(o.shop)return this.shop={type:o.shop,index:0};if(o.inn)return this.inn();if(o.npc)return this.npc(o.npc);}
 chest(o){if(this.s.opened[o.chest])return this.dialog='The chest is empty.';this.s.opened[o.chest]=true;this.addItem(o.item,1);this.dialog=`Found ${SH.DATA.items[o.item]?.name||o.item} ×1!`;}
 npc(id){if(id==='elder'){if(!this.s.flags.metElder){this.s.flags.metElder=true;this.s.autosaveUnlocked=true;this.s.quests.main='cave';this.dialog='Elder Rowan: “Whisperwood has gone silent. Investigate the cave northwest of the village.”';SH.Save.autosave(this.s)}else if(this.s.flags.defeatedStoneback){this.s.quests.main='complete';this.dialog='Elder Rowan: “That fragment bears a star-mark older than Eldenbrook.”';}else this.dialog='Elder Rowan: “The cave lies northwest across the vale.”';}
 else if(id==='lysa'){if(this.s.flags.necklaceDone)this.dialog='Lysa: “Thank you again!”';else if(this.s.flags.necklaceFound){this.s.flags.necklaceDone=true;this.s.gold+=75;this.gainXP(20);this.dialog='Lysa: “My necklace! Please take 75 Gold.”';}else{this.s.quests.necklace='active';this.dialog='Lysa: “I lost Mother’s necklace near the river.”';}}
 else if(id==='necklace'){if(!this.s.flags.necklaceFound){this.s.flags.necklaceFound=true;this.dialog='You find a silver necklace caught in the reeds.'}else this.dialog='Only river grass remains here.';}
 else if(id==='mara'){if(this.s.flags.herbsDone)this.dialog='Mara: “The tonic worked beautifully.”';else if((this.s.inventory.fang||0)>=2){this.s.inventory.fang-=2;this.s.flags.herbsDone=true;this.s.gold+=90;this.gainXP(25);this.dialog='Mara: “Perfect. Take 90 Gold.”';}else{this.s.quests.herbs='active';this.dialog='Mara: “Bring me two Goblin Fangs.”';}}
 else if(id==='spring'){this.s.player.hp=this.s.player.maxHp;this.s.player.mp=this.s.player.maxMp;this.dialog='The spring restores HP and MP.';}
 else if(id==='savepoint'){SH.Save.write('1',this.s);this.dialog='Journey saved to Slot 1.';}
 else if(id==='boss'){if(this.s.flags.defeatedStoneback)this.dialog='Only broken stone remains.';else this.startBattle(['stoneback']);}}
 inn(){if(this.s.gold<20)return this.dialog='Innkeeper: “A room is 20 Gold.”';this.s.gold-=20;this.s.player.hp=this.s.player.maxHp;this.s.player.mp=this.s.player.maxMp;SH.Save.autosave(this.s);this.dialog='You rest until morning. HP and MP restored.';}
 shopInput(a){const list=SH.DATA.shops[this.shop.type];if(a==='cancel'){this.shop=null;return;}if(a==='up')this.shop.index=(this.shop.index+list.length-1)%list.length;if(a==='down')this.shop.index=(this.shop.index+1)%list.length;if(a==='confirm'){const id=list[this.shop.index],obj=SH.DATA.items[id]||SH.DATA.weapons[id]||SH.DATA.armor[id];if(this.s.gold<obj.price){this.notice='Not enough Gold.';this.noticeT=1;return;}this.s.gold-=obj.price;if(SH.DATA.items[id])this.addItem(id,1);else this.s.equipment[id]=(this.s.equipment[id]||0)+1;this.notice=`Bought ${obj.name}`;this.noticeT=1;}}
 menuInput(a){const root=['Items','Equipment','Status','Jobs','Quests','Bestiary','Save','Close'];if(a==='cancel'){if(this.menu.page==='root')this.menu=null;else{this.menu.page='root';this.menu.index=0}return;}if(this.menu.page==='root'){if(a==='up')this.menu.index=(this.menu.index+root.length-1)%root.length;if(a==='down')this.menu.index=(this.menu.index+1)%root.length;if(a==='confirm'){const k=root[this.menu.index];if(k==='Close')this.menu=null;else if(k==='Save'){SH.Save.write('1',this.s);this.notice='Saved to Slot 1';this.noticeT=1.5}else{this.menu.page=k.toLowerCase();this.menu.index=0}}return;}if(this.menu.page==='items'&&a==='confirm'&&(this.s.inventory.potion||0)>0&&this.s.player.hp<this.s.player.maxHp){this.s.inventory.potion--;this.s.player.hp=Math.min(this.s.player.maxHp,this.s.player.hp+60)}if(this.menu.page==='equipment'){const choices=Object.keys(this.s.equipment).filter(k=>this.s.equipment[k]>0);if(a==='up'&&choices.length)this.menu.index=(this.menu.index+choices.length-1)%choices.length;if(a==='down'&&choices.length)this.menu.index=(this.menu.index+1)%choices.length;if(a==='confirm'&&choices.length){const id=choices[this.menu.index],obj=SH.DATA.weapons[id]||SH.DATA.armor[id];this.s.player.equipment[obj.slot]=id;this.notice=`Equipped ${obj.name}`;this.noticeT=1;}}}
 startBattle(ids){this.mode='battle';for(const id of ids)this.s.bestiary[id]=(this.s.bestiary[id]||0)+1;this.battle=new SH.Battle(this,ids);}
 endBattle(win,fled){if(win&&this.battle&&this.battle.boss){this.s.flags.defeatedStoneback=true;this.addItem('fragment',1);this.s.quests.main='return';SH.Save.autosave(this.s);this.dialog='The Ancient Star Fragment hums in Kael’s hand. For an instant, unfamiliar stars fill his vision.';}this.mode='world';this.battle=null;if(fled){this.notice='Escaped safely.';this.noticeT=1;}}
 gameOver(){this.mode='gameover';}
 gainRewards(xp,jp,gold){this.s.gold+=gold;this.gainXP(xp);this.gainJP(jp);}
 gainXP(x){const p=this.s.player;p.xp+=x;while(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.floor(p.nextXp*1.28+20);p.maxHp+=14+p.vit;p.maxMp+=3;p.str+=2;p.vit++;p.agi++;p.hp=p.maxHp;p.mp=p.maxMp;this.notice=`LEVEL UP! Kael reached Lv ${p.level}`;this.noticeT=2;}}
 gainJP(x){const p=this.s.player;p.jp+=x;while(p.jp>=p.nextJp){p.jp-=p.nextJp;p.jobLevel++;p.nextJp=Math.floor(p.nextJp*1.45);this.notice=`JOB LEVEL UP! ${SH.DATA.jobs[p.job].name} Lv ${p.jobLevel}`;this.noticeT=2;}}
 addItem(id,n){this.s.inventory[id]=(this.s.inventory[id]||0)+n;}
 loop(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;if(this.s&&this.mode!=='title')this.s.playtime+=dt;if(this.noticeT>0)this.noticeT-=dt;this.draw();requestAnimationFrame(x=>this.loop(x));}
 draw(){ctx.clearRect(0,0,960,540);if(this.mode==='title')return this.drawTitle();if(this.mode==='battle')return this.drawBattle();if(this.mode==='gameover')return this.drawGameOver();this.drawWorld();if(this.shop)this.drawShop();else if(this.menu)this.drawMenu();else if(this.dialog)this.drawDialog();if(this.noticeT>0)SH.UI.text(ctx,this.notice,480,42,20,'#ffe78d','center');}
 drawTitle(){const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#090c28');g.addColorStop(.55,'#3c315f');g.addColorStop(1,'#12111c');ctx.fillStyle=g;ctx.fillRect(0,0,960,540);for(let i=0;i<70;i++){ctx.fillStyle='rgba(255,245,190,.55)';ctx.fillRect((i*149)%960,(i*83)%250,2,2)}SH.UI.text(ctx,'SAFEHAVEN',480,150,66,'#f1d889','center');SH.UI.text(ctx,'A 16-Bit Fantasy Adventure',480,188,20,'#cfc4ea','center');['NEW GAME','CONTINUE','LOAD GAME','SETTINGS'].forEach((o,i)=>SH.UI.text(ctx,(i===this.titleIndex?'◆ ':'')+o,480,300+i*48,23,i===this.titleIndex?'#ffe99b':'#eee6d4','center'));}
 drawWorld(){const m=SH.MAPS[this.s.map],tw=24,ox=480-this.s.x*tw,oy=270-this.s.y*tw;ctx.fillStyle=m.bg;ctx.fillRect(0,0,960,540);for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++){const sx=ox+x*tw,sy=oy+y*tw;if(sx<-24||sy<-24||sx>960||sy>540)continue;ctx.fillStyle=((x+y)%2)?'rgba(255,255,255,.025)':'rgba(0,0,0,.025)';ctx.fillRect(sx,sy,24,24)}for(const o of m.objects||[]){const x=ox+o.x*tw,y=oy+o.y*tw;ctx.fillStyle=o.npc==='boss'?'#8b7960':o.shop?'#c38b5c':o.inn?'#7c568d':o.chest?'#d0a34e':'#d9d0a4';ctx.fillRect(x-8,y-12,16,20);if(Math.hypot(o.x-this.s.x,o.y-this.s.y)<4)SH.UI.text(ctx,o.label,x,y-18,11,'#fff','center')}ctx.fillStyle='#f0df92';ctx.fillRect(472,258,16,22);SH.UI.text(ctx,m.name,20,28,18,'#fff3cc');SH.UI.text(ctx,`HP ${this.s.player.hp}/${this.s.player.maxHp}   MP ${this.s.player.mp}/${this.s.player.maxMp}   Gold ${this.s.gold}`,20,515,17,'#fff3cc');}
 drawDialog(){SH.UI.panel(ctx,70,390,820,120);SH.UI.text(ctx,this.dialog,95,438,19);SH.UI.text(ctx,'A / Enter',820,488,14,'#d7c884');}
 drawShop(){const list=SH.DATA.shops[this.shop.type];SH.UI.panel(ctx,150,80,660,390,(this.shop.type+' shop').toUpperCase());list.forEach((id,i)=>{const o=SH.DATA.items[id]||SH.DATA.weapons[id]||SH.DATA.armor[id];SH.UI.text(ctx,(i===this.shop.index?'◆ ':'  ')+o.name,190,145+i*45,20,i===this.shop.index?'#ffe99b':'#fff');SH.UI.text(ctx,o.price+' G',690,145+i*45,18,'#d8c877','right')});SH.UI.text(ctx,'Gold: '+this.s.gold,190,430,18);}
 drawBattle(){ctx.fillStyle='#282446';ctx.fillRect(0,0,960,540);this.battle.enemies.forEach((e,i)=>{if(e.hp<=0)return;ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(180+i*120,235,45,0,Math.PI*2);ctx.fill();SH.UI.text(ctx,e.name,180+i*120,310,16,'#fff','center');SH.UI.bar(ctx,130+i*120,325,100,10,e.hp,e.maxHp,'#cf6666')});ctx.fillStyle='#e3d08c';ctx.fillRect(730,210,42,70);SH.UI.panel(ctx,550,330,370,180,'COMMAND');['Attack','Magic','Item','Defend','Flee'].forEach((x,i)=>SH.UI.text(ctx,(i===this.battle.menu?'◆ ':'')+x,585,375+i*26,18,i===this.battle.menu?'#ffe99b':'#fff'));SH.UI.text(ctx,this.battle.message,35,40,19,'#fff');SH.UI.text(ctx,`Kael HP ${this.s.player.hp}/${this.s.player.maxHp} MP ${this.s.player.mp}/${this.s.player.maxMp}`,35,510,18,'#fff3cc');}
 drawMenu(){SH.UI.panel(ctx,110,55,740,430,'MENU');const root=['Items','Equipment','Status','Jobs','Quests','Bestiary','Save','Close'];if(this.menu.page==='root'){root.forEach((x,i)=>SH.UI.text(ctx,(i===this.menu.index?'◆ ':'')+x,160,115+i*42,20,i===this.menu.index?'#ffe99b':'#fff'));SH.UI.text(ctx,`${this.s.player.name}  Lv ${this.s.player.level}  ${SH.DATA.jobs[this.s.player.job].name}`,450,120,23);SH.UI.text(ctx,`HP ${this.s.player.hp}/${this.s.player.maxHp}`,450,160,18);SH.UI.text(ctx,`XP ${this.s.player.xp}/${this.s.player.nextXp}`,450,195,18);SH.UI.text(ctx,`JP ${this.s.player.jp}/${this.s.player.nextJp}`,450,230,18);SH.UI.text(ctx,`Gold ${this.s.gold}`,450,265,18);return;}SH.UI.text(ctx,this.menu.page.toUpperCase(),150,115,23,'#ffe99b');let lines=[];if(this.menu.page==='items')lines=Object.entries(this.s.inventory).filter(([,n])=>n>0).map(([id,n])=>`${SH.DATA.items[id]?.name||id} ×${n}`);if(this.menu.page==='equipment')lines=Object.keys(this.s.equipment).filter(k=>this.s.equipment[k]>0).map((id,i)=>(i===this.menu.index?'◆ ':'')+(SH.DATA.weapons[id]?.name||SH.DATA.armor[id]?.name||id));if(this.menu.page==='status')lines=[`Level ${this.s.player.level}`,`Attack ${this.stats().attack}`,`Defense ${this.stats().defense}`,`Agility ${this.stats().agi}`];if(this.menu.page==='jobs')lines=[`${SH.DATA.jobs[this.s.player.job].name} Lv ${this.s.player.jobLevel}`,`JP ${this.s.player.jp}/${this.s.player.nextJp}`];if(this.menu.page==='quests')lines=Object.entries(this.s.quests).map(([k,v])=>`${SH.DATA.quests[k]?.name||k}: ${v}`);if(this.menu.page==='bestiary')lines=Object.keys(this.s.bestiary).map(id=>`${SH.DATA.enemies[id].name} ×${this.s.bestiary[id]}`);lines.forEach((x,i)=>SH.UI.text(ctx,x,160,160+i*32,18));}
 drawGameOver(){ctx.fillStyle='#090817';ctx.fillRect(0,0,960,540);SH.UI.text(ctx,'GAME OVER',480,240,56,'#d76b78','center');SH.UI.text(ctx,'Press Enter / A to continue from your latest save',480,310,20,'#fff','center');}
}
new Game();
})();