'use strict';
(()=>{
  const base='assets/characters/kael/hd/';
  const defs={idle_down:['overworld/idle/idle_down.png',64,80,1,1,true],idle_left:['overworld/idle/idle_left.png',64,80,1,1,true],idle_right:['overworld/idle/idle_right.png',64,80,1,1,true],idle_up:['overworld/idle/idle_up.png',64,80,1,1,true],walk_down:['overworld/walk/walk_down.png',64,80,8,10,true],walk_left:['overworld/walk/walk_left.png',64,80,8,10,true],walk_right:['overworld/walk/walk_right.png',64,80,8,10,true],walk_up:['overworld/walk/walk_up.png',64,80,8,10,true],run_down:['overworld/run/run_down.png',64,80,8,12,true],run_left:['overworld/run/run_left.png',64,80,8,12,true],run_right:['overworld/run/run_right.png',64,80,8,12,true],run_up:['overworld/run/run_up.png',64,80,8,12,true],battle_idle:['battle/idle/battle_idle.png',128,160,6,6,true],battle_ready:['battle/ready/battle_ready.png',128,160,6,8,true],attack:['battle/attack/attack.png',128,160,10,14,false],heavy_attack:['battle/heavy_attack/heavy_attack.png',128,160,12,12,false],magic:['battle/magic/magic.png',128,160,10,12,false],defend:['battle/defend/defend.png',128,160,6,8,false],battle_hurt:['battle/hurt/battle_hurt.png',128,160,6,12,false],critical:['battle/critical/critical.png',128,160,6,6,true],ko:['battle/ko/ko.png',128,160,10,10,false],victory:['battle/victory/victory.png',128,160,12,10,false],levelup:['battle/levelup/levelup.png',128,160,16,12,false]};
  const animations={},set={id:'kael-hd-base',family:'hd',majorLevel:1,authoritative:true,animations,ready:false,failed:false};let pending=Object.keys(defs).length;
  const settle=()=>{pending--;set.ready=pending===0&&Object.values(animations).some(a=>a.ready);};
  for(const [name,[path,frameW,frameH,frames,fps,loop]] of Object.entries(defs)){const image=new Image(),a=animations[name]={name,image,frameW,frameH,frames,fps,loop,ready:false};image.onload=()=>{a.ready=true;settle()};image.onerror=()=>{a.failed=true;set.failed=true;console.warn(`Kael HD animation failed to load: ${name}`);settle()};image.src=`${base}${path}?v=20260808-kaelhd1`;}
  set.animation=name=>animations[name]?.ready?animations[name]:null;window.SafeHavenKaelHDBase=set;
})();
